language: java

sudo: required

addons:
  apt:
    packages:
      - automake
      - libtool
      - flex
      - bison
      - pkg-config
      - g++

before_install:
  - wget http://www-us.apache.org/dist/thrift/0.9.3/thrift-0.9.3.tar.gz
  - tar xfz thrift-0.9.3.tar.gz
  - cd thrift-0.9.3 && ./configure --without-gnu-ld --without-cpp --without-qt4 --without-c_glib --without-csharp --without-java --without-nodejs --without-erlang --without-python --without-perl --without-php --without-php_extension --without-ruby --without-haskell --without-go --without-d --without-lua && sudo make install && cd ..

